In [1]:
print("Cricintel")

Cricintel

In [2]:
import json

In [4]:
file_path = r"D:\Cricintel\data\raw\335983.json"
with open(file_path, 'r') as file:
    data = json.load(file)

In [5]:
type(data)

dict

In [6]:
data.keys()

dict_keys(['meta', 'info', 'innings'])

In [7]:
type(data['info'])

dict

In [8]:
data['info'].keys()

dict_keys(['balls_per_over', 'city', 'dates', 'event', 'gender', 'match_type', 'officials', 'outcome', 'overs', 'player_of_match', 'players', 'registry', 'season', 'team_type', 'teams', 'toss', 'venue'])

In [9]:
data['info']['teams']

['Kings XI Punjab', 'Chennai Super Kings']

In [ ]:

data['info']['venue']

'Punjab Cricket Association Stadium, Mohali'

In [11]:
data['info']['dates']

['2008-04-19']

In [12]:
type(data['innings'])

list

In [13]:
len(data['innings'])

2

In [14]:
first_inning = data['innings'][0]
type(first_inning)

dict

In [15]:
first_inning.keys()

dict_keys(['team', 'overs', 'powerplays'])

In [16]:
first_inning['team']

'Chennai Super Kings'

In [17]:
type(first_inning['overs'])

list

In [18]:
len(first_inning['overs'])

20

In [19]:
first_over = first_inning['overs'][0]

In [20]:
first_over.keys()

dict_keys(['over', 'deliveries'])

In [21]:
first_over["over"]

0

In [22]:
type(first_over["deliveries"])

list

In [23]:
len(first_over["deliveries"])

6

In [40]:
first_delivery = first_over["deliveries"][0]
first_delivery

{'actual_delivery': '0.1',
 'batter': 'PA Patel',
 'bowler': 'B Lee',
 'non_striker': 'ML Hayden',
 'runs': {'batter': 0, 'extras': 0, 'total': 0}}

In [41]:
first_delivery["runs"]

{'batter': 0, 'extras': 0, 'total': 0}

In [42]:
first_delivery["actual_delivery"]

'0.1'

In [44]:
for delivery in first_over["deliveries"]:
    print(delivery)

{'actual_delivery': '0.1', 'batter': 'PA Patel', 'bowler': 'B Lee', 'non_striker': 'ML Hayden', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}
{'actual_delivery': '0.2', 'batter': 'PA Patel', 'bowler': 'B Lee', 'non_striker': 'ML Hayden', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}
{'actual_delivery': '0.3', 'batter': 'PA Patel', 'bowler': 'B Lee', 'non_striker': 'ML Hayden', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}
{'actual_delivery': '0.4', 'batter': 'ML Hayden', 'bowler': 'B Lee', 'non_striker': 'PA Patel', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}
{'actual_delivery': '0.5', 'batter': 'ML Hayden', 'bowler': 'B Lee', 'non_striker': 'PA Patel', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}
{'actual_delivery': '0.6', 'batter': 'ML Hayden', 'bowler': 'B Lee', 'non_striker': 'PA Patel', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}

In [50]:
for delivery in first_over["deliveries"]:
    delivery_number = delivery["actual_delivery"]
    batsman = delivery["batter"]
    bowler = delivery["bowler"]
    runs = delivery["runs"]["batter"]
    print(f"Delivery: {delivery_number}, Batsman: {batsman}, Bowler: {bowler}, Runs: {runs}")

Delivery: 0.1, Batsman: PA Patel, Bowler: B Lee, Runs: 0
Delivery: 0.2, Batsman: PA Patel, Bowler: B Lee, Runs: 0
Delivery: 0.3, Batsman: PA Patel, Bowler: B Lee, Runs: 1
Delivery: 0.4, Batsman: ML Hayden, Bowler: B Lee, Runs: 0
Delivery: 0.5, Batsman: ML Hayden, Bowler: B Lee, Runs: 4
Delivery: 0.6, Batsman: ML Hayden, Bowler: B Lee, Runs: 0

In [52]:
for over in first_inning["overs"]:
    for delivery in over["deliveries"]:
        delivery_number = delivery["actual_delivery"]
        batsman = delivery["batter"]
        bowler = delivery["bowler"]
        runs = delivery["runs"]["batter"]
        print(f"Delivery: {delivery_number}, Batsman: {batsman}, Bowler: {bowler}, Runs: {runs}")

Delivery: 0.1, Batsman: PA Patel, Bowler: B Lee, Runs: 0
Delivery: 0.2, Batsman: PA Patel, Bowler: B Lee, Runs: 0
Delivery: 0.3, Batsman: PA Patel, Bowler: B Lee, Runs: 1
Delivery: 0.4, Batsman: ML Hayden, Bowler: B Lee, Runs: 0
Delivery: 0.5, Batsman: ML Hayden, Bowler: B Lee, Runs: 4
Delivery: 0.6, Batsman: ML Hayden, Bowler: B Lee, Runs: 0
Delivery: 1.1, Batsman: PA Patel, Bowler: S Sreesanth, Runs: 4
Delivery: 1.2, Batsman: PA Patel, Bowler: S Sreesanth, Runs: 4
Delivery: 1.3, Batsman: PA Patel, Bowler: S Sreesanth, Runs: 4
Delivery: 1.4, Batsman: PA Patel, Bowler: S Sreesanth, Runs: 2
Delivery: 1.5, Batsman: PA Patel, Bowler: S Sreesanth, Runs: 0
Delivery: 1.5, Batsman: PA Patel, Bowler: S Sreesanth, Runs: 0
Delivery: 1.6, Batsman: PA Patel, Bowler: S Sreesanth, Runs: 0
Delivery: 2.1, Batsman: ML Hayden, Bowler: B Lee, Runs: 0
Delivery: 2.2, Batsman: ML Hayden, Bowler: B Lee, Runs: 4
Delivery: 2.2, Batsman: ML Hayden, Bowler: B Lee, Runs: 0
Delivery: 2.3, Batsman: ML Hayden, Bowler: B Lee, Runs: 1
Delivery: 2.4, Batsman: PA Patel, Bowler: B Lee, Runs: 0
Delivery: 2.5, Batsman: MEK Hussey, Bowler: B Lee, Runs: 1
Delivery: 2.6, Batsman: ML Hayden, Bowler: B Lee, Runs: 0
Delivery: 3.1, Batsman: MEK Hussey, Bowler: S Sreesanth, Runs: 0
Delivery: 3.2, Batsman: MEK Hussey, Bowler: S Sreesanth, Runs: 0
Delivery: 3.3, Batsman: MEK Hussey, Bowler: S Sreesanth, Runs: 1
Delivery: 3.4, Batsman: ML Hayden, Bowler: S Sreesanth, Runs: 1
Delivery: 3.5, Batsman: MEK Hussey, Bowler: S Sreesanth, Runs: 0
Delivery: 3.6, Batsman: MEK Hussey, Bowler: S Sreesanth, Runs: 4
Delivery: 4.1, Batsman: ML Hayden, Bowler: B Lee, Runs: 0
Delivery: 4.2, Batsman: ML Hayden, Bowler: B Lee, Runs: 0
Delivery: 4.3, Batsman: MEK Hussey, Bowler: B Lee, Runs: 4
Delivery: 4.4, Batsman: MEK Hussey, Bowler: B Lee, Runs: 4
Delivery: 4.5, Batsman: MEK Hussey, Bowler: B Lee, Runs: 0
Delivery: 4.6, Batsman: MEK Hussey, Bowler: B Lee, Runs: 0
Delivery: 5.1, Batsman: ML Hayden, Bowler: JR Hopes, Runs: 4
Delivery: 5.2, Batsman: ML Hayden, Bowler: JR Hopes, Runs: 6
Delivery: 5.3, Batsman: ML Hayden, Bowler: JR Hopes, Runs: 0
Delivery: 5.4, Batsman: ML Hayden, Bowler: JR Hopes, Runs: 1
Delivery: 5.5, Batsman: MEK Hussey, Bowler: JR Hopes, Runs: 0
Delivery: 5.6, Batsman: MEK Hussey, Bowler: JR Hopes, Runs: 0
Delivery: 6.1, Batsman: ML Hayden, Bowler: IK Pathan, Runs: 4
Delivery: 6.2, Batsman: ML Hayden, Bowler: IK Pathan, Runs: 0
Delivery: 6.3, Batsman: MS Dhoni, Bowler: IK Pathan, Runs: 1
Delivery: 6.4, Batsman: MEK Hussey, Bowler: IK Pathan, Runs: 2
Delivery: 6.5, Batsman: MEK Hussey, Bowler: IK Pathan, Runs: 1
Delivery: 6.6, Batsman: MS Dhoni, Bowler: IK Pathan, Runs: 1
Delivery: 7.1, Batsman: MS Dhoni, Bowler: JR Hopes, Runs: 0
Delivery: 7.2, Batsman: SK Raina, Bowler: JR Hopes, Runs: 1
Delivery: 7.3, Batsman: MEK Hussey, Bowler: JR Hopes, Runs: 0
Delivery: 7.4, Batsman: MEK Hussey, Bowler: JR Hopes, Runs: 1
Delivery: 7.5, Batsman: SK Raina, Bowler: JR Hopes, Runs: 6
Delivery: 7.6, Batsman: SK Raina, Bowler: JR Hopes, Runs: 0
Delivery: 8.1, Batsman: MEK Hussey, Bowler: IK Pathan, Runs: 1
Delivery: 8.2, Batsman: SK Raina, Bowler: IK Pathan, Runs: 4
Delivery: 8.3, Batsman: SK Raina, Bowler: IK Pathan, Runs: 1
Delivery: 8.4, Batsman: MEK Hussey, Bowler: IK Pathan, Runs: 0
Delivery: 8.5, Batsman: MEK Hussey, Bowler: IK Pathan, Runs: 6
Delivery: 8.6, Batsman: MEK Hussey, Bowler: IK Pathan, Runs: 1
Delivery: 9.1, Batsman: MEK Hussey, Bowler: K Goel, Runs: 2
Delivery: 9.2, Batsman: MEK Hussey, Bowler: K Goel, Runs: 1
Delivery: 9.3, Batsman: SK Raina, Bowler: K Goel, Runs: 1
Delivery: 9.4, Batsman: MEK Hussey, Bowler: K Goel, Runs: 0
Delivery: 9.5, Batsman: MEK Hussey, Bowler: K Goel, Runs: 0
Delivery: 9.6, Batsman: MEK Hussey, Bowler: K Goel, Runs: 1
Delivery: 10.1, Batsman: MEK Hussey, Bowler: PP Chawla, Runs: 6
Delivery: 10.2, Batsman: MEK Hussey, Bowler: PP Chawla, Runs: 1
Delivery: 10.3, Batsman: SK Raina, Bowler: PP Chawla, Runs: 2
Delivery: 10.4, Batsman: SK Raina, Bowler: PP Chawla, Runs: 0
Delivery: 10.5, Batsman: SK Raina, Bowler: PP Chawla, Runs: 6
Delivery: 10.6, Batsman: SK Raina, Bowler: PP Chawla, Runs: 4
Delivery: 11.1, Batsman: MEK Hussey, Bowler: K Goel, Runs: 6
Delivery: 11.2, Batsman: MEK Hussey, Bowler: K Goel, Runs: 4
Delivery: 11.3, Batsman: MEK Hussey, Bowler: K Goel, Runs: 1
Delivery: 11.4, Batsman: SK Raina, Bowler: K Goel, Runs: 6
Delivery: 11.5, Batsman: SK Raina, Bowler: K Goel, Runs: 1
Delivery: 11.6, Batsman: MEK Hussey, Bowler: K Goel, Runs: 2
Delivery: 12.1, Batsman: SK Raina, Bowler: WA Mota, Runs: 0
Delivery: 12.1, Batsman: SK Raina, Bowler: WA Mota, Runs: 0
Delivery: 12.2, Batsman: MEK Hussey, Bowler: WA Mota, Runs: 1
Delivery: 12.3, Batsman: JDP Oram, Bowler: WA Mota, Runs: 0
Delivery: 12.3, Batsman: JDP Oram, Bowler: WA Mota, Runs: 0
Delivery: 12.4, Batsman: JDP Oram, Bowler: WA Mota, Runs: 1
Delivery: 12.5, Batsman: MEK Hussey, Bowler: WA Mota, Runs: 1
Delivery: 12.6, Batsman: JDP Oram, Bowler: WA Mota, Runs: 1
Delivery: 13.1, Batsman: JDP Oram, Bowler: JR Hopes, Runs: 1
Delivery: 13.2, Batsman: MEK Hussey, Bowler: JR Hopes, Runs: 0
Delivery: 13.3, Batsman: MEK Hussey, Bowler: JR Hopes, Runs: 1
Delivery: 13.4, Batsman: JDP Oram, Bowler: JR Hopes, Runs: 1
Delivery: 13.5, Batsman: MEK Hussey, Bowler: JR Hopes, Runs: 6
Delivery: 13.6, Batsman: MEK Hussey, Bowler: JR Hopes, Runs: 0
Delivery: 14.1, Batsman: MEK Hussey, Bowler: WA Mota, Runs: 4
Delivery: 14.2, Batsman: MEK Hussey, Bowler: WA Mota, Runs: 1
Delivery: 14.3, Batsman: JDP Oram, Bowler: WA Mota, Runs: 2
Delivery: 14.4, Batsman: JDP Oram, Bowler: WA Mota, Runs: 1
Delivery: 14.5, Batsman: MEK Hussey, Bowler: WA Mota, Runs: 4
Delivery: 14.6, Batsman: MEK Hussey, Bowler: WA Mota, Runs: 6
Delivery: 15.1, Batsman: JDP Oram, Bowler: IK Pathan, Runs: 6
Delivery: 15.2, Batsman: JDP Oram, Bowler: IK Pathan, Runs: 0
Delivery: 15.3, Batsman: JDP Oram, Bowler: IK Pathan, Runs: 0
Delivery: 15.4, Batsman: S Badrinath, Bowler: IK Pathan, Runs: 0
Delivery: 15.5, Batsman: S Badrinath, Bowler: IK Pathan, Runs: 1
Delivery: 15.6, Batsman: MEK Hussey, Bowler: IK Pathan, Runs: 1
Delivery: 16.1, Batsman: MEK Hussey, Bowler: S Sreesanth, Runs: 1
Delivery: 16.2, Batsman: S Badrinath, Bowler: S Sreesanth, Runs: 1
Delivery: 16.3, Batsman: MEK Hussey, Bowler: S Sreesanth, Runs: 6
Delivery: 16.4, Batsman: MEK Hussey, Bowler: S Sreesanth, Runs: 4
Delivery: 16.5, Batsman: MEK Hussey, Bowler: S Sreesanth, Runs: 1
Delivery: 16.6, Batsman: S Badrinath, Bowler: S Sreesanth, Runs: 1
Delivery: 17.1, Batsman: S Badrinath, Bowler: IK Pathan, Runs: 0
Delivery: 17.2, Batsman: S Badrinath, Bowler: IK Pathan, Runs: 4
Delivery: 17.3, Batsman: S Badrinath, Bowler: IK Pathan, Runs: 1
Delivery: 17.4, Batsman: MEK Hussey, Bowler: IK Pathan, Runs: 2
Delivery: 17.5, Batsman: MEK Hussey, Bowler: IK Pathan, Runs: 6
Delivery: 17.6, Batsman: MEK Hussey, Bowler: IK Pathan, Runs: 4
Delivery: 18.1, Batsman: S Badrinath, Bowler: B Lee, Runs: 4
Delivery: 18.2, Batsman: S Badrinath, Bowler: B Lee, Runs: 1
Delivery: 18.3, Batsman: MEK Hussey, Bowler: B Lee, Runs: 1
Delivery: 18.4, Batsman: S Badrinath, Bowler: B Lee, Runs: 1
Delivery: 18.5, Batsman: MEK Hussey, Bowler: B Lee, Runs: 6
Delivery: 18.6, Batsman: MEK Hussey, Bowler: B Lee, Runs: 2
Delivery: 19.1, Batsman: S Badrinath, Bowler: JR Hopes, Runs: 6
Delivery: 19.2, Batsman: S Badrinath, Bowler: JR Hopes, Runs: 6
Delivery: 19.3, Batsman: S Badrinath, Bowler: JR Hopes, Runs: 4
Delivery: 19.4, Batsman: S Badrinath, Bowler: JR Hopes, Runs: 1
Delivery: 19.5, Batsman: MEK Hussey, Bowler: JR Hopes, Runs: 6
Delivery: 19.6, Batsman: MEK Hussey, Bowler: JR Hopes, Runs: 2

In [56]:
total_runs = 0
for over in first_inning["overs"]:
    for delivery in over["deliveries"]:
        runs = delivery["runs"]["batter"]
        if delivery["batter"]=="PA Patel":
            total_runs += runs
print(total_runs)

15

In [58]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.8 MB 5.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.8 MB 5.5 MB/s eta 0:00:02
   ----------- ---------------------------- 2.9/9.8 MB 5.2 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.8 MB 5.4 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.8 MB 5.7 MB/s eta 0:00:01
   ------------------------------- -------- 7.6/9.8 MB 6.1 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 6.3 MB/s  0:00:01
Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.6/12.7 MB 7.7 MB/s eta 0:00:02
   --------- ------------------------------ 3.1/12.7 MB 7.9 MB/s eta 0:00:02
   --------------- ------------------------ 5.0/12.7 MB 8.0 MB/s eta 0:00:01
   -------------------- ------------------- 6.6/12.7 MB 7.7 MB/s eta 0:00:01
   ------------------------ --------------- 7.9/12.7 MB 7.3 MB/s eta 0:00:01
   ---------------------------- ----------- 9.2/12.7 MB 7.2 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.7 MB 7.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.7 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 6.5 MB/s  0:00:01
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\admin\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [59]:
import pandas as pd

print(pd.__version__)

3.0.6

In [60]:
import json
from pathlib import Path
import pandas as pd

raw_folder = Path("../data/raw")

json_files = list(raw_folder.glob("*.json"))

print("Number of matches:", len(json_files))
print(json_files[:5])

Number of matches: 1243
[WindowsPath('../data/raw/1082591.json'), WindowsPath('../data/raw/1082592.json'), WindowsPath('../data/raw/1082593.json'), WindowsPath('../data/raw/1082594.json'), WindowsPath('../data/raw/1082595.json')]

In [85]:
records = []

for file_path in json_files:

    with open(file_path, "r", encoding="utf-8") as file:
        match = json.load(file)

    match_id = file_path.stem

    info = match["info"]

    dates = info.get("dates", [])
    match_date = dates[0] if dates else None

    venue = info.get("venue")
    city = info.get("city")

    teams = info.get("teams", [])

    for innings_number, innings in enumerate(match["innings"], start=1):

        batting_team = innings["team"]
        bowling_team = next(
    (team for team in teams if team != batting_team),
    None
)

        for over in innings["overs"]:

            over_number = over["over"]

            for delivery in over["deliveries"]:
                extras = delivery.get("extras", {})
                wides = extras.get("wides", 0)
                noballs = extras.get("noballs", 0)
                byes = extras.get("byes", 0)
                legbyes = extras.get("legbyes", 0)
                is_legal_delivery = wides == 0 and noballs == 0
                wickets = delivery.get("wickets", [])
                is_wicket = len(wickets) > 0;
                record = {
                    "match_id": match_id,
                    "date": match_date,
                    "city": city,
                    "venue": venue,
                    "innings": innings_number,
                    "batting_team": batting_team,
                    "bowling_team": bowling_team,
                    "over": over_number,
                    "wides": wides,
                    "noballs": noballs,
                    "byes": byes,
                    "legbyes": legbyes,
                    "is_legal_delivery": is_legal_delivery,
                    "is_wicket": is_wicket,
                    "delivery": delivery.get("actual_delivery"),
                    "batter": delivery["batter"],
                    "non_striker": delivery["non_striker"],
                    "bowler": delivery["bowler"],
                    "batter_runs": delivery["runs"]["batter"],
                    "extra_runs": delivery["runs"]["extras"],
                    "total_runs": delivery["runs"]["total"]
                    
                }

                records.append(record)

In [86]:
df = pd.DataFrame(records)

df.head()

,match_id,date,city,venue,innings,batting_team,bowling_team,over,wides,noballs,...,legbyes,is_legal_delivery,is_wicket,delivery,batter,non_striker,bowler,batter_runs,extra_runs,total_runs
0,1082591,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,0,0,...,0,True,False,0.1,DA Warner,S Dhawan,TS Mills,0,0,0
1,1082591,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,0,0,...,0,True,False,0.2,DA Warner,S Dhawan,TS Mills,0,0,0
2,1082591,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,0,0,...,0,True,False,0.3,DA Warner,S Dhawan,TS Mills,4,0,4
3,1082591,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,0,0,...,0,True,False,0.4,DA Warner,S Dhawan,TS Mills,0,0,0
4,1082591,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,2,0,...,0,False,False,0.5,DA Warner,S Dhawan,TS Mills,0,2,2

In [63]:
df.shape

(295732, 14)

In [69]:
print("Pandas version:", pd.__version__)
print("Shape:", df.shape)
print("Unique matches:", df["match_id"].nunique())
print("Unique batters:", df["batter"].nunique())

Pandas version: 3.0.6
Shape: (295732, 14)
Unique matches: 1243
Unique batters: 738

In [70]:
def get_phase(over):
    if over < 6:
        return "Powerplay"
    elif over < 15:
        return "Middle"
    else:
        return "Death"

df["phase"] = df["over"].apply(get_phase)

In [71]:
df[["over", "phase"]].head(20)

    over      phase
0      0  Powerplay
1      0  Powerplay
2      0  Powerplay
3      0  Powerplay
4      0  Powerplay
5      0  Powerplay
6      0  Powerplay
7      1  Powerplay
8      1  Powerplay
9      1  Powerplay
10     1  Powerplay
11     1  Powerplay
12     1  Powerplay
13     1  Powerplay
14     2  Powerplay
15     2  Powerplay
16     2  Powerplay
17     2  Powerplay
18     2  Powerplay
19     2  Powerplay

In [72]:
df["phase"].value_counts()

phase
Middle       135655
Powerplay     92904
Death         67173
Name: count, dtype: int64

In [73]:
df["is_boundary"] = df["batter_runs"].isin([4, 6])

df["is_dot"] = df["total_runs"] == 0

In [74]:
df["date"] = pd.to_datetime(df["date"])

df["season"] = df["date"].dt.year

In [75]:
df["season"].value_counts().sort_index()

season
2008    13489
2009    13606
2010    14498
2011    17013
2012    17767
2013    18177
2014    14300
2015    13652
2016    14096
2017    13862
2018    14286
2019    14312
2020    14559
2021    14425
2022    17912
2023    17863
2024    17103
2025    17285
2026    17527
Name: count, dtype: int64

In [77]:
processed_folder = Path("../data/processed")
processed_folder.mkdir(parents=True, exist_ok=True)

In [78]:
df.to_csv(
    processed_folder / "ipl_deliveries.csv",
    index=False
)

In [87]:
print(df.shape)
print(df.columns.tolist())

(295732, 21)
['match_id', 'date', 'city', 'venue', 'innings', 'batting_team', 'bowling_team', 'over', 'wides', 'noballs', 'byes', 'legbyes', 'is_legal_delivery', 'is_wicket', 'delivery', 'batter', 'non_striker', 'bowler', 'batter_runs', 'extra_runs', 'total_runs']

In [88]:
for file_path in json_files:
    with open(file_path, "r", encoding="utf-8") as file:
        match = json.load(file)

    found = False

    for innings in match["innings"]:
        for over in innings["overs"]:
            for delivery in over["deliveries"]:

                if "wickets" in delivery or "extras" in delivery:
                    print(delivery)
                    found = True
                    break

            if found:
                break
        if found:
            break

    if found:
        break

{'actual_delivery': '0.5', 'batter': 'DA Warner', 'bowler': 'TS Mills', 'extras': {'wides': 2}, 'non_striker': 'S Dhawan', 'runs': {'batter': 0, 'extras': 2, 'total': 2}}

In [89]:
df.to_csv("../data/processed/ipl_deliveries.csv", index=False)

In [90]:
print("Shape:", df.shape)
print("Matches:", df["match_id"].nunique())
print("Wicket events:", df["is_wicket"].sum())
print("Wides:", df["wides"].sum())
print("No-balls:", df["noballs"].sum())
print("Legal deliveries:", df["is_legal_delivery"].sum())

Shape: (295732, 21)
Matches: 1243
Wicket events: 14705
Wides: 11795
No-balls: 1261
Legal deliveries: 284630

In [93]:
df.head()

,match_id,date,city,venue,innings,batting_team,bowling_team,over,wides,noballs,...,legbyes,is_legal_delivery,is_wicket,delivery,batter,non_striker,bowler,batter_runs,extra_runs,total_runs
0,1082591,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,0,0,...,0,True,False,0.1,DA Warner,S Dhawan,TS Mills,0,0,0
1,1082591,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,0,0,...,0,True,False,0.2,DA Warner,S Dhawan,TS Mills,0,0,0
2,1082591,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,0,0,...,0,True,False,0.3,DA Warner,S Dhawan,TS Mills,4,0,4
3,1082591,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,0,0,...,0,True,False,0.4,DA Warner,S Dhawan,TS Mills,0,0,0
4,1082591,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,2,0,...,0,False,False,0.5,DA Warner,S Dhawan,TS Mills,0,2,2

In [94]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 295732 entries, 0 to 295731
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           295732 non-null  str
 1   date               295732 non-null  str
 2   city               283335 non-null  str
 3   venue              295732 non-null  str
 4   innings            295732 non-null  int64
 5   batting_team       295732 non-null  str
 6   bowling_team       295732 non-null  str
 7   over               295732 non-null  int64
 8   wides              295732 non-null  int64
 9   noballs            295732 non-null  int64
 10  byes               295732 non-null  int64
 11  legbyes            295732 non-null  int64
 12  is_legal_delivery  295732 non-null  bool
 13  is_wicket          295732 non-null  bool
 14  delivery           295732 non-null  str
 15  batter             295732 non-null  str
 16  non_striker        295732 non-null  str
 17  bowler             295732 non-null  str
 18  batter_runs        295732 non-null  int64
 19  extra_runs         295732 non-null  int64
 20  total_runs         295732 non-null  int64
dtypes: bool(2), int64(9), str(10)
memory usage: 43.4 MB

In [95]:
# Convert date to datetime
df["date"] = pd.to_datetime(df["date"])

# Season
df["season"] = df["date"].dt.year

# Match phase
def get_phase(over):
    if over < 6:
        return "Powerplay"
    elif over < 15:
        return "Middle"
    else:
        return "Death"

df["phase"] = df["over"].apply(get_phase)

# Boundary delivery
df["is_boundary"] = df["batter_runs"].isin([4, 6])

# Dot ball
df["is_dot"] = df["total_runs"] == 0

# Ball faced by batter
df["ball_faced"] = (df["wides"] == 0).astype(int)

In [96]:
print(df.shape)
print(df.columns.tolist())

(295732, 26)
['match_id', 'date', 'city', 'venue', 'innings', 'batting_team', 'bowling_team', 'over', 'wides', 'noballs', 'byes', 'legbyes', 'is_legal_delivery', 'is_wicket', 'delivery', 'batter', 'non_striker', 'bowler', 'batter_runs', 'extra_runs', 'total_runs', 'season', 'phase', 'is_boundary', 'is_dot', 'ball_faced']

In [97]:
top_run_scorers = (
    df.groupby("batter")["batter_runs"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_run_scorers

batter
V Kohli           9346
RG Sharma         7331
S Dhawan          6769
DA Warner         6567
KL Rahul          5828
SK Raina          5536
MS Dhoni          5439
AM Rahane         5367
AB de Villiers    5181
SV Samson         5181
Name: batter_runs, dtype: int64

In [98]:
batter_stats = (
    df.groupby("batter")
      .agg(
          runs=("batter_runs", "sum"),
          balls=("ball_faced", "sum"),
          boundaries=("is_boundary", "sum"),
          dot_balls=("is_dot", "sum")
      )
      .reset_index()
)

In [ ]:
batter_stats["strike_rate"] = (
    batter_stats["runs"] / batter_stats["balls"] * 100
).round(2)

batter_stats["boundary_pct"] = (
    batter_stats["boundaries"] / batter_stats["balls"] * 100
).round(2)

batter_stats["dot_ball_pct"] = (
    batter_stats["dot_balls"] / batter_stats["balls"] * 100
).round(2)

In [100]:
top10_analysis = (
    batter_stats
    .sort_values("runs", ascending=False)
    .head(10)
)

top10_analysis

,batter,runs,balls,boundaries,dot_balls,strike_rate,boundary_pct,dot_ball_pct
693,V Kohli,9346,6930,1164,2180,134.86,16.80,31.46
526,RG Sharma,7331,5517,985,2022,132.88,17.85,36.65
563,S Dhawan,6769,5326,921,1879,127.09,17.29,35.28
159,DA Warner,6567,4702,899,1628,139.66,19.12,34.62
311,KL Rahul,5828,4188,748,1322,139.16,17.86,31.57
597,SK Raina,5536,4046,710,1276,136.83,17.55,31.54
409,MS Dhoni,5439,3957,639,1248,137.45,16.15,31.54
52,AM Rahane,5367,4273,681,1486,125.60,15.94,34.78
31,AB de Villiers,5181,3411,667,983,151.89,19.55,28.82
627,SV Samson,5181,3671,675,1215,141.13,18.39,33.10

In [101]:
phase_stats = (
    df.groupby(["batter", "phase"])
      .agg(
          runs=("batter_runs", "sum"),
          balls=("ball_faced", "sum"),
          boundaries=("is_boundary", "sum"),
          dots=("is_dot", "sum")
      )
      .reset_index()
)

phase_stats["strike_rate"] = (
    phase_stats["runs"] / phase_stats["balls"] * 100
).round(2)

phase_stats["boundary_pct"] = (
    phase_stats["boundaries"] / phase_stats["balls"] * 100
).round(2)

phase_stats["dot_ball_pct"] = (
    phase_stats["dots"] / phase_stats["balls"] * 100
).round(2)

In [102]:
comparison = phase_stats[
    phase_stats["batter"].isin(["V Kohli", "AB de Villiers"])
]

comparison.sort_values(["batter", "phase"])

,batter,phase,runs,balls,boundaries,dots,strike_rate,boundary_pct,dot_ball_pct
69,AB de Villiers,Death,1868,838,275,151,222.91,32.82,18.02
70,AB de Villiers,Middle,2572,1959,272,536,131.29,13.88,27.36
71,AB de Villiers,Powerplay,741,614,120,296,120.68,19.54,48.21
1518,V Kohli,Death,1573,835,212,184,188.38,25.39,22.04
1519,V Kohli,Middle,4286,3407,427,927,125.80,12.53,27.21
1520,V Kohli,Powerplay,3487,2688,525,1069,129.72,19.53,39.77

In [103]:
import sqlite3

conn = sqlite3.connect("../sql/cricintel.db")

df.to_sql(
    "deliveries",
    conn,
    if_exists="replace",
    index=False
)

print("Database created!")

Database created!

In [104]:
query = """
SELECT COUNT(*) AS total_deliveries
FROM deliveries;
"""

pd.read_sql_query(query, conn)

   total_deliveries
0            295732

In [105]:
query = """
SELECT
    batter,
    SUM(batter_runs) AS total_runs
FROM deliveries
GROUP BY batter
ORDER BY total_runs DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

           batter  total_runs
0         V Kohli        9346
1       RG Sharma        7331
2        S Dhawan        6769
3       DA Warner        6567
4        KL Rahul        5828
5        SK Raina        5536
6        MS Dhoni        5439
7       AM Rahane        5367
8       SV Samson        5181
9  AB de Villiers        5181

In [106]:
query = """
SELECT
    batter,
    phase,
    SUM(batter_runs) AS runs,
    SUM(ball_faced) AS balls,
    ROUND(
        100.0 * SUM(batter_runs) / NULLIF(SUM(ball_faced), 0),
        2
    ) AS strike_rate,
    SUM(is_boundary) AS boundaries
FROM deliveries
GROUP BY batter, phase
HAVING SUM(ball_faced) >= 100
ORDER BY strike_rate DESC;
"""

phase_sql = pd.read_sql_query(query, conn)

phase_sql.head(15)

             batter      phase  runs  balls  strike_rate  boundaries
0     V Suryavanshi     Middle   334    146       228.77          53
1     V Suryavanshi  Powerplay   665    293       226.96         119
2    AB de Villiers      Death  1868    838       222.91         275
3    LS Livingstone      Death   345    159       216.98          52
4        RM Patidar      Death   267    124       215.32          42
5   J Fraser-McGurk  Powerplay   298    144       206.94          57
6   B Sai Sudharsan      Death   308    149       206.71          45
7        MA Agarwal      Death   252    122       206.56          36
8         Q de Kock      Death   240    117       205.13          37
9          CH Gayle      Death   581    284       204.58          89
10          RR Pant      Death  1095    540       202.78         171
11    Priyansh Arya     Middle   231    116       199.14          34
12         T Stubbs      Death   546    275       198.55          76
13      Tilak Varma      Death   543    274       198.18          81
14        JP Inglis  Powerplay   307    155       198.06          54

In [107]:
query = """
SELECT
    batter,
    SUM(batter_runs) AS death_runs,
    SUM(ball_faced) AS balls,
    ROUND(
        100.0 * SUM(batter_runs) / NULLIF(SUM(ball_faced), 0),
        2
    ) AS strike_rate,
    SUM(is_boundary) AS boundaries,
    ROUND(
        100.0 * SUM(is_boundary) / NULLIF(SUM(ball_faced), 0),
        2
    ) AS boundary_pct
FROM deliveries
WHERE phase = 'Death'
GROUP BY batter
HAVING SUM(ball_faced) >= 300
ORDER BY strike_rate DESC
LIMIT 15;
"""

death_specialists = pd.read_sql_query(query, conn)

death_specialists

            batter  death_runs  balls  strike_rate  boundaries  boundary_pct
0   AB de Villiers        1868    838       222.91         275         32.82
1          RR Pant        1095    540       202.78         171         31.67
2       AD Russell        1432    731       195.90         227         31.05
3         TH David         843    432       195.14         119         27.55
4       JC Buttler         804    417       192.81         113         27.10
5        H Klaasen         738    383       192.69          98         25.59
6        SV Samson         852    446       191.03         121         27.13
7         RK Singh         791    417       189.69         120         28.78
8          V Kohli        1573    835       188.38         212         25.39
9          SS Iyer         820    443       185.10         114         25.73
10       RG Sharma        1527    843       181.14         220         26.10
11    Yuvraj Singh         906    501       180.84         130         25.95
12      MP Stoinis         980    542       180.81         139         25.65
13    F du Plessis         568    316       179.75          77         24.37
14        KL Rahul         907    507       178.90         122         24.06

In [108]:
query = """
SELECT
    batter,
    bowler,
    SUM(batter_runs) AS runs,
    SUM(ball_faced) AS balls,
    ROUND(
        100.0 * SUM(batter_runs) / NULLIF(SUM(ball_faced), 0),
        2
    ) AS strike_rate,
    SUM(is_boundary) AS boundaries,
    SUM(is_wicket) AS wicket_events
FROM deliveries
GROUP BY batter, bowler
HAVING SUM(ball_faced) >= 30
ORDER BY runs DESC
LIMIT 20;
"""

matchups = pd.read_sql_query(query, conn)

matchups

,batter,bowler,runs,balls,strike_rate,boundaries,wicket_events
0,DA Warner,SP Narine,195,123,158.54,29,2
1,V Kohli,R Ashwin,181,149,121.48,19,1
2,V Kohli,RA Jadeja,179,160,111.88,15,5
3,SK Raina,PP Chawla,175,101,173.27,25,4
4,RG Sharma,UT Yadav,170,118,144.07,29,5
5,V Kohli,UT Yadav,168,96,175.00,26,5
6,V Kohli,JJ Bumrah,164,110,149.09,23,5
7,V Kohli,A Mishra,162,105,154.29,21,3
8,KL Rahul,DL Chahar,160,103,155.34,25,1
9,V Kohli,DJ Bravo,157,103,152.43,21,2
10,DA Warner,YS Chahal,156,96,162.50,17,2
11,KL Rahul,JJ Bumrah,150,122,122.95,17,3
12,V Kohli,SP Narine,149,141,105.67,13,4
13,KL Rahul,YS Chahal,148,97,152.58,17,2
14,KL Rahul,Mohammed Siraj,147,91,161.54,25,3
15,S Dhawan,Harbhajan Singh,147,120,122.50,21,4
16,AM Rahane,PP Chawla,146,101,144.55,20,3
17,RG Sharma,PP Chawla,146,115,126.96,18,2
18,RG Sharma,SP Narine,145,137,105.84,18,9
19,GJ Maxwell,R Ashwin,141,72,195.83,20,4

In [109]:
query = """
SELECT
    batting_team,
    phase,
    SUM(total_runs) AS runs,
    SUM(is_legal_delivery) AS legal_balls,
    ROUND(
        100.0 * SUM(total_runs) /
        NULLIF(SUM(is_legal_delivery), 0),
        2
    ) AS scoring_rate,
    SUM(is_boundary) AS boundaries,
    SUM(is_wicket) AS wicket_events
FROM deliveries
GROUP BY batting_team, phase
ORDER BY batting_team, phase;
"""

team_phase = pd.read_sql_query(query, conn)

team_phase.head(20)

,batting_team,phase,runs,legal_balls,scoring_rate,boundaries,wicket_events
0,Chennai Super Kings,Death,12392,7145,173.44,1510,496
1,Chennai Super Kings,Middle,18646,14208,131.24,1969,570
2,Chennai Super Kings,Powerplay,12562,9545,131.61,1871,358
3,Deccan Chargers,Death,3133,2032,154.18,355,198
4,Deccan Chargers,Middle,4913,4020,122.21,500,177
5,Deccan Chargers,Powerplay,3417,2700,126.56,502,109
6,Delhi Capitals,Death,5230,3108,168.28,653,263
7,Delhi Capitals,Middle,8543,6362,134.28,937,281
8,Delhi Capitals,Powerplay,6186,4302,143.79,985,201
9,Delhi Daredevils,Death,6272,3902,160.74,775,312
10,Delhi Daredevils,Middle,10664,8459,126.07,1088,368
11,Delhi Daredevils,Powerplay,7360,5795,127.01,1094,272
12,Gujarat Lions,Death,1159,749,154.74,136,64
13,Gujarat Lions,Middle,2144,1604,133.67,236,80
14,Gujarat Lions,Powerplay,1559,1086,143.55,243,44
15,Gujarat Titans,Death,3660,2036,179.76,467,166
16,Gujarat Titans,Middle,6085,4151,146.59,689,160
17,Gujarat Titans,Powerplay,3998,2772,144.23,602,90
18,Kings XI Punjab,Death,7875,4980,158.13,936,431
19,Kings XI Punjab,Middle,13235,10063,131.52,1417,440

In [110]:
death_specialists

            batter  death_runs  balls  strike_rate  boundaries  boundary_pct
0   AB de Villiers        1868    838       222.91         275         32.82
1          RR Pant        1095    540       202.78         171         31.67
2       AD Russell        1432    731       195.90         227         31.05
3         TH David         843    432       195.14         119         27.55
4       JC Buttler         804    417       192.81         113         27.10
5        H Klaasen         738    383       192.69          98         25.59
6        SV Samson         852    446       191.03         121         27.13
7         RK Singh         791    417       189.69         120         28.78
8          V Kohli        1573    835       188.38         212         25.39
9          SS Iyer         820    443       185.10         114         25.73
10       RG Sharma        1527    843       181.14         220         26.10
11    Yuvraj Singh         906    501       180.84         130         25.95
12      MP Stoinis         980    542       180.81         139         25.65
13    F du Plessis         568    316       179.75          77         24.37
14        KL Rahul         907    507       178.90         122         24.06

In [111]:
df["is_four"] = (df["batter_runs"] == 4).astype(int)
df["is_six"] = (df["batter_runs"] == 6).astype(int)

In [112]:
print("Fours:", df["is_four"].sum())
print("Sixes:", df["is_six"].sum())

Fours: 34447
Sixes: 15779

In [113]:
df.to_csv(
    "../data/processed/ipl_deliveries.csv",
    index=False
)

In [114]:
df.to_csv(
    "../data/processed/ipl_deliveries.csv",
    index=False
)